services:
  postgres_abcd:
    image: postgres:15
    restart: unless-stopped
    container_name: postgres_abcd
    env_file: ".env"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  web:
    build: .
    command: >
      sh -c "sleep 5 &&
             uv sync --frozen --no-install-project --no-dev &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 --workers 3 config.wsgi:application"
    container_name: abcd00
    env_file: ".env"
    volumes:
      - ./config:/app/config
      - ./manage.py:/app/manage.py
      - ./dynamic_form:/app/dynamic_form
      - ./staticfiles:/app/staticfiles
    depends_on:
      postgres_abcd:
        condition: service_healthy
    restart: always

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres_abcd
      ADMINER_DESIGN: nette

  nginx:
    image: nginx:1.21
    container_name: nginx_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/app/staticfiles:ro
    ports:
      - "8000:80"
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume: